---
services:
  acos-prometheus-exporter:
    image: "ghcr.io/vveliev-tc/acos-prometheus-exporter:local"
    container_name: acos-prometheus-exporter
    build:
      context: .
      dockerfile: ./build/Dockerfile
      target: build
    ports:
      - "9734:9734"
    command: ["--config", "/local/config.yml"]
    volumes:
      # - ./examples/:/local/
      - ./.ci/:/local/
      - ./:/app/

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      # - ./examples/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./.ci/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    command: "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_USERS_ALLOW_ORG_CREATE=false
      - GF_USERS_AUTO_ASSIGN_ORG=true
      - GF_USERS_AUTO_ASSIGN_ORG_ROLE=Viewer
    volumes:
      - ./grafana:/var/lib/grafana

volumes:
  grafana:
    driver: local
